# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa38728dbad40295fb77c429eea33b65329982581e64c9954479e7109762f8c3e0b284f525fada2bd588c8cce31a5e7ec82798bdbe604e60ddcad66b39cb735a

test:
  secret_key_base: 8f8395c35c325b26a3db17dab751f8afa1dba9bd7087fea1db24ef33c7f4d2c9e35118b24aa62f2dbb6cb942d5e8baf46d8fa568c23cbef6512b5ef2cdfc2834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
